spring.application.name=BusTicketBooking

# DB Connection
spring.datasource.url=jdbc:mysql://localhost:3306/fastx_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}


jwt.secret=hsdjfghsdjfh348534857348jsdhjsdhfjsdgh8478457hdgjfh478
# Hibernate Settings

spring.jpa.hibernate.ddl-auto=update
